### ISSUE TITLE
Question regarding OAEI tracks Evaluation

### ISSUE THREAD

**Issue by sefeoglu** [dwslab/melt#87]
Hello,
I would like to evaluate my matcher`s  results using your framework, but the framework could not download OAEI conference tracks. 
Have you ever face any problem like this ?
or 
How could I evaluate my results ?

Thanks 🙏

**Comment by sven-h** [comment]
Hi,

what version do you use (maven central, developer version or cloned from github)?
In case you use the maven central version, please try out the [developer version with jitpack](https://github.com/dwslab/melt).
The repositories of SEALS changed because their server are shut down.

We will soon (before the OAEI) create a new release in maven central (version 3.0).
Let me know if the new version fixes the issue.

Best regards
Sven

**Comment by sven-h** [comment]
I hope it works now.
If you have further questions, please file a new issue.
